### ISSUE TITLE
Language preference ignored

### ISSUE THREAD

**Issue by ldx63** [oheil/NOCC#1]
Good afternoon,
I'd like to use NOCC in English, in order to use standard reply tags (i.e., "Re: "). When I set preferred language in preferences, it is kept until the end of the session. 
On any new login, however, the language is defaulted to the one used for the login page, the browser default language, ignoring the saved language in preferences.

Thank you
Aldo

**Comment by oheil** [comment]
Do you have the language selector visible on the login page? This is a drop down selector beneath the password field.

**Comment by ldx63** [comment]
Yes, there is the language selector on the login page. The problem is that its value is always the browser default (Italian in my case), and the preference I saved is ignored.
Each login, I have to select manually the English language.

**Comment by oheil** [comment]
Yes, I understand. This is not a bug, but a problem.

First you can work around by setting a bookmark to
https://your.domain/index.php?lang=en
This should set english as language, when opening the NOCC login page using this bookmark. 

The problem is, that NOCC can't use the preferences as the user is not known before login time. Should NOCC overwrite what is chosen at login with what it founds after login in the preferences? This could be surprising too.

I am open for suggestions and ideas...

**Comment by ldx63** [comment]
Thanks, for the time being I'll use the URL command you suggested.

Possible solution: 
I think that saved preference should prevail over the browser default.
In practice: In the login page, one more option should be available and made default: "Use language saved in your preferences (if any)"; or better, just a blank default selection. For users who never saved preferences, the language will fall back to the browser settings after login.
If the user chooses a different language at login, the current behaviour is held, i.e., login-chosen language overrides preferences.

Kind regards
Aldo

**Comment by ldx63** [comment]
Curiously, I've just realized that the "correct" behavior is applied to the Theme selection: i.e., the theme saved in preferences always overrides the theme selected in the login page.

**Comment by ldx63** [comment]
A simpler solution would also be to just delete selection of language and theme at login: use saved ones, if any, or system default if the user never saved them.

**Comment by oheil** [comment]
> In practice: In the login page, one more option should be available and made default: "Use language saved in your preferences (if any)".

I thought of that too. 

> A simpler solution would also be to just delete selection of language and theme at login: use saved ones, if any, or system default if the user never saved them.

This can already be done in the server side configuration.

Thanks for your thoughts (more of course welcome).

**Comment by ldx63** [comment]
> This can already be done in the server side configuration.

Ops, I didn't know this. :-)

Thank you very much,
Aldo

**Comment by oheil** [comment]
It needs a change in the next release.
My favorite is currently:
- The login page is shown in the default browser language (or config default lang according to the configuration set).
- The selected language in the drop down box is "use user preference" (or similar, "standard", ...)
    - After login:
        - if there is a language preference it is used
        - if there is none, the same language as on the login screen is used
- if at login screen the language is explicitly set, this language is used and preference is ignored until next login
- same logic holds for "theme"

**Comment by ldx63** [comment]
Looks good to me, thank you very much!
Aldo

**Comment by oheil** [comment]
It can be used already using the main branch.

**Comment by ldx63** [comment]
Thank you very much!
I'll give it a try soon.
Kind regards
Aldo

**Comment by oheil** [comment]
Issue solved and implemented since 1.9.12  February 28, 2023.
